name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  workflow_dispatch:

jobs:
  analyze:
    name: PHPStan analysis
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        php:
          - "8.1"
          - "8.2"
          - "8.3"

    steps:
      - uses: actions/checkout@v5

      - name: Setup PHP
        uses: pmmp/setup-php-action@3.2.0
        with:
          php-version: ${{ matrix.php }}
          install-path: "./bin"
          pm-version-major: 5

      - name: Restore Composer package cache
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: "~/.cache/composer"
          key: "php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}"
          restore-keys: "php-${{ matrix.php }}-composer-"

      - name: Install PHPStan Composer dependencies
        working-directory: ./phpstan
        run: composer install --prefer-dist --no-interaction

      - name: Run PHPStan
        working-directory: ./phpstan
        run: vendor/bin/phpstan analyze

  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5

      - name: Setup PHP
        uses: pmmp/setup-php-action@3.2.0
        with:
          php-version: 8.3
          install-path: "./bin"
          pm-version-major: 5

      - name: Build to .phar
        run: php -dphar.readonly=0 ./tools/DevToolsConsoleScript.php --relative ./ --make ./ --out VoiceCraft.phar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: VoiceCraft.phar
          path: ./VoiceCraft.phar